---
- name: Install iptables-persistent
  apt:
   name: iptables-persistent
   state: present
  notify: enable netfilter-persistent

# Allow related and established connections
- name: Allow related and established connections ipv4
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    ip_version: ipv4
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"

# Allow related and established connections
- name: Allow related and established connections ipv6
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    ip_version: ipv6
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"

- name: Allow new incoming SYN packets on TCP port 22 (SSH). ipv4
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    ctstate: NEW
    syn: match
    jump: ACCEPT
    ip_version: ipv4
    comment: Accept new SSH connections.
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"


# icmp codes
# https://www.reddit.com/r/networking/comments/2sc12s/allowing_icmp_through_firewalls/
# https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-codes-0
# echo code 8
# echo reply code 0
# destination unreachable 3
# time exceeded 11
# paremeter problem 12
- name: Enable ICMP incoming ipv4
  iptables:
    chain: INPUT
    protocol: ICMP
    icmp_type: '8'
    jump: ACCEPT
    ip_version: ipv4
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"

- name: Enable ICMP incoming ipv4
  iptables:
    chain: INPUT
    protocol: ICMP
    icmp_type: '0'
    jump: ACCEPT
    ip_version: ipv4
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"

- name: Enable ICMP incoming ipv4
  iptables:
    chain: INPUT
    protocol: ICMP
    icmp_type: '11'
    jump: ACCEPT
    ip_version: ipv4
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"

- name: Enable ICMP incoming ipv4
  iptables:
    chain: INPUT
    protocol: ICMP
    icmp_type: '12'
    jump: ACCEPT
    ip_version: ipv4
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"

- name: Enable ICMP incoming ipv4
  iptables:
    chain: INPUT
    protocol: ICMP
    icmp_type: '8'
    jump: ACCEPT
    ip_version: ipv4
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"

# Getting errors on this
# --icmpv6-type 8 : unknown option
#- name: Enable ICMP incoming ipv6
#  iptables:
#    chain: INPUT
#    protocol: ICMP
#    icmp_type: 8
#    jump: ACCEPT
#    ip_version: ipv6
#  notify: "save iptables"

- name: Allow localhost connections
  iptables:
    chain: INPUT
    jump: ACCEPT
    in_interface: lo
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"

- name: Set the policy for the INPUT chain to DROP ipv4
  iptables:
    chain: INPUT
    policy: DROP
    ip_version: ipv4
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"

- name: Set the policy for the INPUT chain to DROP ipv6
  iptables:
    chain: INPUT
    policy: DROP
    ip_version: ipv6
  notify: "save iptables"
  when: ansible_virtualization_type != "docker"